import { useEffect, useMemo, useState } from 'react';
import { Activity, Boxes, ExternalLink, Link2, RefreshCw, Send, ShieldCheck, Sparkles, Workflow } from 'lucide-react';
import type { Incident, WorkspaceState } from './domain';
import { SpatialSurface } from './TrueSpatial';
import { XFACTOR_FABRIX_CAPABILITIES, XFACTOR_FABRIX_PRODUCT_ID, fabrixHealth, fabrixLaunchHub, fabrixOpenProduct, fabrixProducts, fabrixPublishProject, type FabrixHealth, type FabrixProduct } from './fabrixClient';

type Props={workspace:WorkspaceState;currentIncident?:Incident;onNotice:(message:string)=>void};
const capSet=new Set<string>(XFACTOR_FABRIX_CAPABILITIES);
const list=(value:unknown):string[]=>Array.isArray(value)?value.filter((item):item is string=>typeof item==='string'):[];
const matches=(product:FabrixProduct)=>list(product.manifest?.accepts).filter(cap=>capSet.has(cap));
const family=(product:FabrixProduct)=>typeof product.manifest?.family==='string'?product.manifest.family:'fabriX';
function projectPayload(workspace:WorkspaceState,currentIncident?:Incident){const id=currentIncident?.id??'xfactor-workspace';return{schema_version:'1.0',project_id:`xfactor:${id}`,source_product_id:XFACTOR_FABRIX_PRODUCT_ID,source:'xFactor.OS',name:currentIncident?.name??'xFactor.OS Workspace',status:currentIncident?.status??'workspace',priority:currentIncident?.priority,next_move:currentIncident?.nextMove,updated_at:new Date().toISOString(),counts:{incidents:workspace.incidents.filter(item=>!item.archived).length,signals:workspace.signals.length,assets:workspace.assets.filter(item=>!item.archived).length,piles:workspace.piles.length},capabilities:['repo.project-state','project.snapshot','project.evidence'],policy:{publish:'explicit-user-action',entitlement_authority:'xfactor-os'}}}
export default function FabrixSuiteRoom({workspace,currentIncident,onNotice}:Props){
 const[health,setHealth]=useState<FabrixHealth>();const[products,setProducts]=useState<FabrixProduct[]>([]);const[error,setError]=useState('');const[busy,setBusy]=useState('');const[activity,setActivity]=useState<string[]>([]);
 async function refresh(){setError('');try{const[h,p]=await Promise.all([fabrixHealth(),fabrixProducts()]);setHealth(h);setProducts(p.products);if(h.error&&h.transport!=='desktop-required')setError(h.error)}catch(err){setError(err instanceof Error?err.message:String(err))}}
 useEffect(()=>{void refresh()},[]);
 const ranked=useMemo(()=>[...products].sort((a,b)=>matches(b).length-matches(a).length||a.name.localeCompare(b.name)),[products]);const compatible=ranked.filter(product=>matches(product).length>0);
 async function publishProject(openAfter?:FabrixProduct){const key=openAfter?.product_id??'project';setBusy(key);setError('');try{const result=await fabrixPublishProject(projectPayload(workspace,currentIncident));const mode=result.mode==='rpc'?'PUBLISHED TO HUB':'STAGED IN FABRIX HOME';setActivity(prev=>[`${mode} // ${currentIncident?.name??'WORKSPACE'}`,...prev].slice(0,8));if(openAfter){await fabrixOpenProduct(openAfter.product_id);setActivity(prev=>[`OPENED // ${openAfter.name} WITH CURRENT PROJECT CONTEXT`,...prev].slice(0,8))}onNotice(openAfter?`FABRIX // OPENED ${openAfter.name.toUpperCase()}`:`FABRIX // ${mode}`)}catch(err){setError(err instanceof Error?err.message:String(err))}finally{setBusy('')}}
 async function openProduct(product:FabrixProduct){setBusy(product.product_id);setError('');try{await fabrixOpenProduct(product.product_id);setActivity(prev=>[`OPENED // ${product.name}`,...prev].slice(0,8));onNotice(`FABRIX // OPENED ${product.name.toUpperCase()}`)}catch(err){setError(err instanceof Error?err.message:String(err))}finally{setBusy('')}}
 async function openHub(uri='fabrix://open'){setError('');try{await fabrixLaunchHub(uri)}catch(err){setError(err instanceof Error?err.message:String(err))}}
 const connected=Boolean(health?.connected);
 return <section className="xf-page fx-suite-room">
  <div className="xf-section-head fx-suite-head"><div><span className="kicker">fabriX SUITE //</span><h1>CONNECTED DAMAGE.</h1><p>xFactor.OS stays the power tool. fabriX is the nervous system around it: products, projects, assets, artifacts and workflows move through one declared capability contract.</p></div><div className="xf-floor-actions"><button onClick={()=>void refresh()}><RefreshCw size={14}/> REFRESH</button><button className="pink" onClick={()=>void openHub()}><ExternalLink size={14}/> OPEN HUB</button></div></div>
  <div className="fx-suite-status-grid">
   <SpatialSurface className="fx-suite-status" group="fabrix-status"><small>HUB LINK</small><b className={connected?'online':'offline'}>{connected?'CONNECTED':'OFFLINE'}</b><span>{health?.hub_version??(health?.transport==='desktop-required'?'DESKTOP BRIDGE REQUIRED':'HUB NOT DETECTED')}</span></SpatialSurface>
   <SpatialSurface className="fx-suite-status" group="fabrix-status"><small>ADAPTER</small><b>v{health?.adapter_version??'1.0.0'}</b><span>{health?.transport?.replaceAll('-',' ').toUpperCase()??'CHECKING'}</span></SpatialSurface>
   <SpatialSurface className="fx-suite-status" group="fabrix-status"><small>CURRENT PROJECT</small><b>{currentIncident?.name??'WORKSPACE'}</b><span>{currentIncident?.status??'NO INCIDENT SELECTED'}</span></SpatialSurface>
   <SpatialSurface className="fx-suite-status secure" group="fabrix-status"><small>ENTITLEMENT</small><b><ShieldCheck size={14}/> xFACTOR AUTHORITY</b><span>fabriX registration never grants a software license.</span></SpatialSurface>
  </div>
  {error&&<div className="fx-suite-error">{error}</div>}
  {!connected&&<div className="fx-suite-callout"><Link2 size={18}/><div><b>{health?.transport==='desktop-required'?'INSTALL / OPEN THE DESKTOP BUILD':'FABRIX HUB IS NOT RUNNING'}</b><p>{health?.transport==='desktop-required'?'The PWA can describe the suite contract, but local Hub discovery and product launch remain native-only by design.':'Launch fabriX Hub and hit Refresh. xFactor.OS only talks to the loopback port published by Hub; it does not scan the machine for products.'}</p></div><button onClick={()=>void openHub()}>OPEN HUB</button></div>}
  <div className="fx-suite-grid">
   <section className="fx-suite-panel launcher"><div className="fx-suite-panel-title"><Boxes size={15}/><div><b>SUITE LAUNCHER</b><small>{products.length} REGISTERED / MANAGED · {compatible.length} CURRENT MATCHES</small></div></div><div className="fx-suite-products">{ranked.length===0?<div className="fx-suite-empty">NO HUB PRODUCTS REPORTED YET.</div>:ranked.map(product=>{const shared=matches(product);return <SpatialSurface as="article" className="fx-product-card" group="fabrix-products" spatialId={product.product_id} spatialDraggable key={product.product_id}><div className="fx-product-top"><span>{family(product).toUpperCase()}</span><i>{shared.length?`${shared.length} MATCHES`:'REGISTERED'}</i></div><h3>{product.name}</h3><p>{product.version??'VERSION NOT DECLARED'}</p><div className="fx-product-caps">{shared.slice(0,3).map(cap=><code key={cap}>{cap}</code>)}{shared.length===0&&<code>NO CURRENT CAPABILITY MATCH</code>}</div><div className="fx-product-actions"><button disabled={!connected||busy===product.product_id} onClick={()=>void openProduct(product)}>OPEN</button><button disabled={!connected||busy===product.product_id} onClick={()=>void publishProject(product)}><Send size={11}/> WITH PROJECT</button></div></SpatialSurface>})}</div></section>
   <aside className="fx-suite-side">
    <section className="fx-suite-panel"><div className="fx-suite-panel-title"><Workflow size={15}/><div><b>QUICK WORKFLOWS</b><small>CONTEXTUAL HANDOFFS</small></div></div><button className="fx-workflow" disabled={!currentIncident} onClick={()=>void publishProject()}><Sparkles size={14}/><span><b>PUBLISH CURRENT PROJECT STATE</b><small>Incident metadata + evidence counts → fabriX</small></span></button><button className="fx-workflow" onClick={()=>void openHub('fabrix://workflow?source=planetx.xfactor-os')}><Workflow size={14}/><span><b>OPEN FULL WORKFLOW BUILDER</b><small>Graph / Matrix / City / Pipeline live in Hub</small></span></button><button className="fx-workflow" onClick={()=>void openHub('fabrix://open?section=assets')}><Boxes size={14}/><span><b>OPEN ASSET LIBRARY</b><small>Browse reusable source material without duplicating the library here</small></span></button></section>
    <section className="fx-suite-panel"><div className="fx-suite-panel-title"><Activity size={15}/><div><b>LOCAL HANDOFF TAPE</b><small>THIS SESSION</small></div></div><div className="fx-suite-activity">{activity.length?activity.map((item,index)=><span key={index}>{item}</span>):<p>No fabriX handoffs in this session yet.</p>}</div></section>
   </aside>
  </div>
 </section>
}
