import { MonitorCog, RotateCcw, SlidersHorizontal } from 'lucide-react';
import type { M6Settings, UiDensity, WorkbenchPreset } from './m6Settings';

export default function M6SettingsPanel({settings,onPatch,onReset}:{settings:M6Settings;onPatch:(changes:Partial<M6Settings>)=>void;onReset:()=>void}){
  return <section className="xf-page m6-settings">
    <div className="xf-section-head"><div><span className="kicker">SETTINGS //</span><h1>TUNE THE DAMAGE.</h1><p>Presentation preferences stay device-local. Canonical project data remains untouched.</p></div><button className="xf-big-action" onClick={onReset}><RotateCcw size={15}/> RESET UI SETTINGS</button></div>
    <div className="m6-settings-grid">
      <section><h2><MonitorCog/> ACCESSIBILITY + READABILITY</h2><label>UI SCALE <b>{Math.round(settings.uiScale*100)}%</b><input type="range" min=".95" max="1.35" step=".05" value={settings.uiScale} onChange={e=>onPatch({uiScale:Number(e.target.value)})}/></label><label>DENSITY<select value={settings.density} onChange={e=>onPatch({density:e.target.value as UiDensity})}><option value="comfortable">COMFORTABLE</option><option value="dense">DENSE</option><option value="wide">WIDE</option></select></label><label className="toggle"><input type="checkbox" checked={settings.reducedMotion} onChange={e=>onPatch({reducedMotion:e.target.checked})}/> REDUCE MOTION</label></section>
      <section><h2><SlidersHorizontal/> SPATIAL ENGINE</h2><label>PLASMA QUALITY <b>{Math.round(settings.plasmaQuality*100)}%</b><input type="range" min=".55" max="1.15" step=".05" value={settings.plasmaQuality} onChange={e=>onPatch({plasmaQuality:Number(e.target.value)})}/></label><label>STARTING GAP <b>{settings.spatialGap}px</b><input type="range" min="32" max="150" step="8" value={settings.spatialGap} onChange={e=>onPatch({spatialGap:Number(e.target.value)})}/></label><p>More gap prevents cards from arriving pre-fused. Lower Plasma quality reduces mode-switch GPU cost.</p></section>
      <section><h2>BROWSER + CAPTURE</h2><label>OFFLINE CAPTURE DEPTH<select value={settings.browserCaptureDepth} onChange={e=>onPatch({browserCaptureDepth:Number(e.target.value) as 0|1|2})}><option value="0">CURRENT PAGE ONLY</option><option value="1">PAGE + 1 LEVEL</option><option value="2">PAGE + 2 LEVELS</option></select></label><p>Site capture is intentionally bounded. M6 snapshots publicly retrievable client assets; it does not extract server source, bypass paywalls, or defeat DRM.</p></section>
      <section><h2>WORKBENCH</h2><label>DEFAULT VIEW<select value={settings.defaultWorkbenchPreset} onChange={e=>onPatch({defaultWorkbenchPreset:e.target.value as WorkbenchPreset})}><option value="cockpit">COCKPIT</option><option value="code">CODE FOCUS</option><option value="preview">PREVIEW FOCUS</option><option value="debug">DEBUG</option></select></label><label className="toggle"><input type="checkbox" checked={settings.confirmDestructive} onChange={e=>onPatch({confirmDestructive:e.target.checked})}/> CONFIRM DESTRUCTIVE ACTIONS</label></section>
    </div>
  </section>;
}
