import { Gauge, HelpCircle, RotateCcw, SlidersHorizontal, Sparkles, X } from 'lucide-react';
import type { OsSettings } from './osSettings';

export default function SettingsPanel({settings,onPatch,onReset,onClose}:{settings:OsSettings;onPatch:(changes:Partial<OsSettings>)=>void;onReset:()=>void;onClose:()=>void}){
  return <div className="xf-settings-backdrop" onMouseDown={onClose}>
    <section className="xf-settings" onMouseDown={event=>event.stopPropagation()}>
      <header><div><span>SETTINGS //</span><h2>CONTROL THE CHAOS.</h2><p>Device-local presentation and workspace behavior. Project data stays separate.</p></div><button onClick={onClose}><X size={18}/></button></header>
      <div className="xf-settings-grid">
        <article><h3><Gauge/> READABILITY</h3><label>UI SCALE <b>{Math.round(settings.uiScale*100)}%</b><input type="range" min=".9" max="1.5" step=".02" value={settings.uiScale} onChange={e=>onPatch({uiScale:Number(e.target.value)})}/></label><label>ICON SCALE <b>{Math.round(settings.iconScale*100)}%</b><input type="range" min=".9" max="1.5" step=".02" value={settings.iconScale} onChange={e=>onPatch({iconScale:Number(e.target.value)})}/></label><label className="setting-toggle"><input type="checkbox" checked={settings.hoverHelp} onChange={e=>onPatch({hoverHelp:e.target.checked})}/><span><b>HOVER EXPLANATIONS</b><small>Explain status data, controls, and navigation when you pause over them.</small></span></label></article>
        <article><h3><Sparkles/> SPATIAL ENGINE</h3><label>MOTION<select value={settings.motion} onChange={e=>onPatch({motion:e.target.value as OsSettings['motion']})}><option value="full">FULL PHYSICS</option><option value="reduced">REDUCED MOTION</option></select></label><label>QUALITY<select value={settings.spatialQuality} onChange={e=>onPatch({spatialQuality:e.target.value as OsSettings['spatialQuality']})}><option value="performance">PERFORMANCE</option><option value="balanced">BALANCED</option><option value="high">HIGH</option></select></label><small>Mode switching temporarily freezes layout while WebGL surfaces register, preventing the five-second visual scramble.</small></article>
        <article><h3><SlidersHorizontal/> WORKBENCH</h3><label>DEFAULT VIEW<select value={settings.workbenchPreset} onChange={e=>onPatch({workbenchPreset:e.target.value as OsSettings['workbenchPreset']})}><option value="balanced">BALANCED</option><option value="code">CODE FOCUS</option><option value="preview">PREVIEW FOCUS</option><option value="terminal">TERMINAL FOCUS</option></select></label><label className="setting-toggle"><input type="checkbox" checked={settings.compactRail} onChange={e=>onPatch({compactRail:e.target.checked})}/><span><b>COMPACT RAIL</b><small>Reduce dev-tool rail spacing on smaller displays.</small></span></label></article>
        <article><h3><HelpCircle/> xBROWSER CAPTURE</h3><label>DEFAULT CRAWL DEPTH<select value={settings.browserCaptureDepth} onChange={e=>onPatch({browserCaptureDepth:Number(e.target.value) as OsSettings['browserCaptureDepth']})}><option value="0">CURRENT PAGE ONLY</option><option value="1">PAGE + 1 LEVEL</option><option value="2">PAGE + 2 LEVELS</option><option value="3">PAGE + 3 LEVELS</option></select></label><small>Capture is explicit, same-origin, bounded, and intended for public or authorized material. It does not bypass logins, DRM, or access controls.</small></article>
      </div>
      <footer><button onClick={onReset}><RotateCcw size={14}/> RESET DEVICE SETTINGS</button><button className="primary" onClick={onClose}>DONE</button></footer>
    </section>
  </div>;
}
