import { useEffect, useRef, useState } from 'react';
import ToolShell from './ToolShell';

type SeedMode='edges'|'point';
interface Prefs{tolerance:number;seedMode:SeedMode;feather:number;}
const KEY='xfactor-studio-bgremove2-';const LEGACY='xos-studio-bgremove-';const FALLBACK:Prefs={tolerance:32,seedMode:'edges',feather:0};
function load(boardId:string):Prefs{try{const raw=localStorage.getItem(KEY+boardId);if(raw)return{...FALLBACK,...JSON.parse(raw)};const old=localStorage.getItem(LEGACY+boardId);if(old)return{...FALLBACK,...JSON.parse(old)};}catch{}return FALLBACK;}
function downloadBlob(blob:Blob,name:string){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),3000);}

export default function BackgroundRemover({boardId,onExit}:{boardId:string;onExit:()=>void}){
 const [prefs,setPrefs]=useState<Prefs>(()=>load(boardId));const [hasImage,setHasImage]=useState(false);const [fileName,setFileName]=useState('');const [seed,setSeed]=useState<{x:number;y:number}|null>(null);const [removed,setRemoved]=useState(0);const canvasRef=useRef<HTMLCanvasElement>(null);const original=useRef<ImageData|null>(null);const objectUrl=useRef<string|null>(null);
 useEffect(()=>{try{localStorage.setItem(KEY+boardId,JSON.stringify(prefs));}catch{}},[boardId,prefs]);
 useEffect(()=>()=>{if(objectUrl.current)URL.revokeObjectURL(objectUrl.current);},[]);
 function onFile(file:File){if(objectUrl.current)URL.revokeObjectURL(objectUrl.current);const u=URL.createObjectURL(file);objectUrl.current=u;const img=new Image();img.onload=()=>{const c=canvasRef.current;if(!c)return;c.width=img.naturalWidth;c.height=img.naturalHeight;const ctx=c.getContext('2d',{willReadFrequently:true});if(!ctx)return;ctx.drawImage(img,0,0);original.current=ctx.getImageData(0,0,c.width,c.height);setFileName(file.name);setHasImage(true);setSeed(null);run(prefs,null);};img.onerror=()=>setHasImage(false);img.src=u;}
 function run(p:Prefs,point:{x:number;y:number}|null=seed){const c=canvasRef.current,srcData=original.current;if(!c||!srcData)return;const ctx=c.getContext('2d',{willReadFrequently:true});if(!ctx)return;const w=c.width,h=c.height,src=srcData.data,out=new Uint8ClampedArray(src),visited=new Uint8Array(w*h),queue=new Int32Array(w*h);let head=0,tail=0,removedCount=0;const push=(i:number)=>{if(i<0||i>=w*h||visited[i])return;visited[i]=1;queue[tail++]=i;};
   let reference:number|null=null;if(p.seedMode==='point'&&point){reference=(Math.max(0,Math.min(h-1,point.y))*w+Math.max(0,Math.min(w-1,point.x)))*4;push(reference/4);}else{for(let x=0;x<w;x++){push(x);push((h-1)*w+x);}for(let y=0;y<h;y++){push(y*w);push(y*w+w-1);}}
   const dist=(a:number,b:number)=>Math.hypot(src[a]-src[b],src[a+1]-src[b+1],src[a+2]-src[b+2]);
   while(head<tail){const idx=queue[head++],x=idx%w,y=(idx/w)|0,px=idx*4;removedCount++;out[px+3]=0;const ns=[idx-1,idx+1,idx-w,idx+w];for(const ni of ns){if(ni<0||ni>=w*h||visited[ni])continue;const nx=ni%w,ny=(ni/w)|0;if(Math.abs(nx-x)+Math.abs(ny-y)!==1)continue;const npx=ni*4;const compare=reference??px;if(dist(compare,npx)<=p.tolerance)push(ni);}}
   if(p.feather>0){const alpha=new Uint8ClampedArray(w*h);for(let i=0;i<w*h;i++)alpha[i]=out[i*4+3];for(let pass=0;pass<p.feather;pass++){const next=new Uint8ClampedArray(alpha);for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){const i=y*w+x;if(alpha[i]===0)continue;const min=Math.min(alpha[i-1],alpha[i+1],alpha[i-w],alpha[i+w]);if(min<255)next[i]=Math.max(0,Math.min(alpha[i],min+80));}alpha.set(next);}for(let i=0;i<w*h;i++)out[i*4+3]=alpha[i];}
   ctx.putImageData(new ImageData(out,w,h),0,0);setRemoved(Math.round(removedCount/(w*h)*100));}
 function setPref(patch:Partial<Prefs>){setPrefs(p=>{const next={...p,...patch};queueMicrotask(()=>run(next));return next;});}
 function canvasClick(e:React.PointerEvent<HTMLCanvasElement>){if(!hasImage||prefs.seedMode!=='point')return;const c=canvasRef.current;if(!c)return;const r=c.getBoundingClientRect(),x=Math.max(0,Math.min(c.width-1,Math.floor((e.clientX-r.left)*c.width/r.width))),y=Math.max(0,Math.min(c.height-1,Math.floor((e.clientY-r.top)*c.height/r.height)));const pt={x,y};setSeed(pt);run(prefs,pt);}
 function reset(){const c=canvasRef.current,src=original.current;if(c&&src)c.getContext('2d',{willReadFrequently:true})?.putImageData(src,0,0);setRemoved(0);}
 function download(){const c=canvasRef.current;if(!c)return;c.toBlob(b=>b&&downloadBlob(b,`${fileName.replace(/\.[^.]+$/,'')||'image'}-no-bg.png`),'image/png');}
 return <ToolShell title="BACKGROUND REMOVER 2.0" onExit={onExit}><div className="toolCol" data-testid="background-remover-2-root"><label className="toolDrop"><input aria-label="Background image" type="file" accept="image/*" hidden onChange={e=>e.target.files?.[0]&&onFile(e.target.files[0])}/>{fileName?`LOADED: ${fileName}`:'UPLOAD IMAGE'}</label><div className="toolHint">Deterministic color-connected removal for flat/near-flat backgrounds. Use EDGE AUTO for studio-style backgrounds, or PICK BACKGROUND then click the canvas. This is not ML subject segmentation.</div>
 <div className="toolRow"><button className={`chip ${prefs.seedMode==='edges'?'on':''}`} onClick={()=>setPref({seedMode:'edges'})}>EDGE AUTO</button><button className={`chip ${prefs.seedMode==='point'?'on':''}`} onClick={()=>setPref({seedMode:'point'})}>PICK BACKGROUND</button></div>
 <label className="toolField">TOLERANCE {prefs.tolerance}<input aria-label="Background tolerance" type="range" min="4" max="140" value={prefs.tolerance} onChange={e=>setPref({tolerance:Number(e.target.value)})}/></label><label className="toolField">EDGE FEATHER {prefs.feather}<input aria-label="Edge feather" type="range" min="0" max="4" value={prefs.feather} onChange={e=>setPref({feather:Number(e.target.value)})}/></label>
 {hasImage&&<div className="toolRow"><button className="wbtn ghost" onClick={reset}>RESET</button><button className="wbtn" onClick={download}>DOWNLOAD TRANSPARENT PNG</button><span className="toolHint">~{removed}% pixels removed{prefs.seedMode==='point'&&!seed?' · click background to sample':''}</span></div>}
 <div className="toolCanvasWrap" style={{background:'repeating-conic-gradient(#20232a 0 25%,#11141a 0 50%) 50%/20px 20px'}}><canvas ref={canvasRef} onPointerDown={canvasClick} style={{maxWidth:640,height:'auto',cursor:prefs.seedMode==='point'?'crosshair':'default'}}/></div></div></ToolShell>;
}