import { useEffect, useMemo, useRef, useState } from 'react';
import ToolShell from './ToolShell';
import { ICONS } from '../../../design-system/icons/registry';
import type { IconName } from '../../../design-system/icons/registry';

type Layout='iconLeft'|'iconTop'|'iconOnly'|'wordOnly';type Shape='none'|'circle'|'roundedSquare'|'square';type Ratio='wide'|'square';
interface LogoPrefs{icon:IconName;word:string;sub:string;layout:Layout;shape:Shape;fg:string;bg:string;accent:string;size:number;transparent:boolean;ratio:Ratio;}
const CHOICE_NAMES=['hexagon','bolt','sparkles','star','diamond','penTool','brush','wand','stamp','telescope','sprout','globe','music','camera','idea','branch','grid','layers','checkCircle'];
const CHOICES:IconName[]=CHOICE_NAMES.filter(n=>n in ICONS) as IconName[];const KEY='xfactor-studio-logo2-',LEGACY='xos-studio-logo-';
const fallback:LogoPrefs={icon:'hexagon',word:'BRAND',sub:'',layout:'iconLeft',shape:'roundedSquare',fg:'#E6F4FF',bg:'#05080D',accent:'#00F5FF',size:720,transparent:false,ratio:'wide'};
function load(boardId:string):LogoPrefs{try{const raw=localStorage.getItem(KEY+boardId);if(raw)return{...fallback,...JSON.parse(raw)};const old=localStorage.getItem(LEGACY+boardId);if(old)return{...fallback,...JSON.parse(old)};}catch{}return fallback;}
function dl(blob:Blob,name:string){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),3000);}
const safe=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]||c));
async function iconSvg(name:IconName,color:string){const {renderToStaticMarkup}=await import('react-dom/server');const C=ICONS[name];let xml=renderToStaticMarkup(<C size={256} strokeWidth={1.6} color={color}/>);if(!xml.includes('xmlns='))xml=xml.replace('<svg','<svg xmlns="http://www.w3.org/2000/svg"');return xml;}
async function iconImage(name:IconName,color:string){const xml=await iconSvg(name,color);return await new Promise<HTMLImageElement>((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src='data:image/svg+xml;base64,'+btoa(unescape(encodeURIComponent(xml)));});}

export default function LogoMaker({boardId,onExit}:{boardId:string;onExit:()=>void}){
 const [prefs,setPrefs]=useState<LogoPrefs>(()=>load(boardId));const [busy,setBusy]=useState(false);const canvasRef=useRef<HTMLCanvasElement>(null);const choices=useMemo(()=>CHOICES,[]);
 useEffect(()=>{try{localStorage.setItem(KEY+boardId,JSON.stringify(prefs));}catch{}},[boardId,prefs]);
 useEffect(()=>{let cancelled=false;const c=canvasRef.current;if(!c)return;setBusy(true);const W=prefs.size,H=prefs.ratio==='square'?prefs.size:Math.round(prefs.size*.62);c.width=W;c.height=H;const ctx=c.getContext('2d');if(!ctx)return;const drawBadge=(cx:number,cy:number,r:number)=>{if(prefs.shape==='none')return;ctx.fillStyle=prefs.accent;ctx.beginPath();if(prefs.shape==='circle')ctx.arc(cx,cy,r,0,Math.PI*2);else{const s=r*1.9,rr=prefs.shape==='roundedSquare'?s*.22:0,x=cx-s/2,y=cy-s/2;ctx.roundRect(x,y,s,s,rr);}ctx.fill();};
   (async()=>{ctx.clearRect(0,0,W,H);if(!prefs.transparent){ctx.fillStyle=prefs.bg;ctx.fillRect(0,0,W,H);}const showIcon=prefs.layout!=='wordOnly',showWord=prefs.layout!=='iconOnly',iconSize=Math.min(H*.55,W*.28);let img:HTMLImageElement|null=null;if(showIcon){try{img=await iconImage(prefs.icon,prefs.shape==='none'?prefs.accent:'#05080D');}catch{}}if(cancelled)return;ctx.textBaseline='middle';
   if(prefs.layout==='iconLeft'){const cx=W*.2,cy=H/2,r=iconSize*.65;drawBadge(cx,cy,r);if(img)ctx.drawImage(img,cx-iconSize*.4,cy-iconSize*.4,iconSize*.8,iconSize*.8);if(showWord){ctx.fillStyle=prefs.fg;ctx.font=`600 ${Math.round(H*.24)}px Orbitron, sans-serif`;ctx.fillText(prefs.word.toUpperCase(),W*.34,prefs.sub?H*.43:H/2);if(prefs.sub){ctx.fillStyle=prefs.accent;ctx.font=`400 ${Math.round(H*.105)}px monospace`;ctx.fillText(prefs.sub.toUpperCase(),W*.34,H*.68);}}}
   else if(prefs.layout==='iconTop'){const cx=W/2,cy=H*.33,r=iconSize*.58;drawBadge(cx,cy,r);if(img)ctx.drawImage(img,cx-iconSize*.38,cy-iconSize*.38,iconSize*.76,iconSize*.76);if(showWord){ctx.fillStyle=prefs.fg;ctx.textAlign='center';ctx.font=`600 ${Math.round(H*.18)}px Orbitron, sans-serif`;ctx.fillText(prefs.word.toUpperCase(),W/2,H*.72);if(prefs.sub){ctx.fillStyle=prefs.accent;ctx.font=`400 ${Math.round(H*.08)}px monospace`;ctx.fillText(prefs.sub.toUpperCase(),W/2,H*.84);}ctx.textAlign='left';}}
   else if(prefs.layout==='iconOnly'){const r=Math.min(W,H)*.34;drawBadge(W/2,H/2,r);if(img)ctx.drawImage(img,W/2-r*.72,H/2-r*.72,r*1.44,r*1.44);}
   else{ctx.fillStyle=prefs.fg;ctx.textAlign='center';ctx.font=`600 ${Math.round(H*.25)}px Orbitron, sans-serif`;ctx.fillText(prefs.word.toUpperCase(),W/2,prefs.sub?H*.44:H/2);if(prefs.sub){ctx.fillStyle=prefs.accent;ctx.font=`400 ${Math.round(H*.1)}px monospace`;ctx.fillText(prefs.sub.toUpperCase(),W/2,H*.66);}ctx.textAlign='left';}setBusy(false);})();return()=>{cancelled=true;};},[prefs]);
 function baseName(){return(prefs.word||'logo').trim().toLowerCase().replace(/[^a-z0-9]+/g,'-')||'logo';}
 function exportPng(){canvasRef.current?.toBlob(b=>b&&dl(b,`${baseName()}-${prefs.size}.png`),'image/png');}
 async function exportSvg(){const W=prefs.size,H=prefs.ratio==='square'?prefs.size:Math.round(prefs.size*.62),showIcon=prefs.layout!=='wordOnly',showWord=prefs.layout!=='iconOnly';let iconInner='';if(showIcon){const xml=await iconSvg(prefs.icon,prefs.shape==='none'?prefs.accent:'#05080D');iconInner=xml.replace(/^.*?<svg[^>]*>/s,'').replace(/<\/svg>.*$/s,'');}const iconSize=Math.min(H*.55,W*.28);let body='';const badge=(cx:number,cy:number,r:number)=>prefs.shape==='none'?'':prefs.shape==='circle'?`<circle cx="${cx}" cy="${cy}" r="${r}" fill="${prefs.accent}"/>`:`<rect x="${cx-r*.95}" y="${cy-r*.95}" width="${r*1.9}" height="${r*1.9}" rx="${prefs.shape==='roundedSquare'?r*.42:0}" fill="${prefs.accent}"/>`;const icon=(cx:number,cy:number,s:number)=>`<svg x="${cx-s*.4}" y="${cy-s*.4}" width="${s*.8}" height="${s*.8}" viewBox="0 0 24 24">${iconInner}</svg>`;
   if(prefs.layout==='iconLeft'){const cx=W*.2,cy=H/2,r=iconSize*.65;body+=badge(cx,cy,r)+(showIcon?icon(cx,cy,iconSize):'');if(showWord){body+=`<text x="${W*.34}" y="${prefs.sub?H*.46:H*.54}" fill="${prefs.fg}" font-family="Orbitron,sans-serif" font-size="${H*.24}" font-weight="600">${safe(prefs.word.toUpperCase())}</text>`;if(prefs.sub)body+=`<text x="${W*.34}" y="${H*.71}" fill="${prefs.accent}" font-family="monospace" font-size="${H*.105}">${safe(prefs.sub.toUpperCase())}</text>`;}}
   else if(prefs.layout==='iconTop'){const cx=W/2,cy=H*.33,r=iconSize*.58;body+=badge(cx,cy,r)+(showIcon?icon(cx,cy,iconSize):'');if(showWord){body+=`<text x="${W/2}" y="${H*.76}" text-anchor="middle" fill="${prefs.fg}" font-family="Orbitron,sans-serif" font-size="${H*.18}" font-weight="600">${safe(prefs.word.toUpperCase())}</text>`;if(prefs.sub)body+=`<text x="${W/2}" y="${H*.87}" text-anchor="middle" fill="${prefs.accent}" font-family="monospace" font-size="${H*.08}">${safe(prefs.sub.toUpperCase())}</text>`;}}
   else if(prefs.layout==='iconOnly'){const r=Math.min(W,H)*.34;body+=badge(W/2,H/2,r)+(showIcon?`<svg x="${W/2-r*.72}" y="${H/2-r*.72}" width="${r*1.44}" height="${r*1.44}" viewBox="0 0 24 24">${iconInner}</svg>`:'');}
   else{body+=`<text x="${W/2}" y="${prefs.sub?H*.48:H*.54}" text-anchor="middle" fill="${prefs.fg}" font-family="Orbitron,sans-serif" font-size="${H*.25}" font-weight="600">${safe(prefs.word.toUpperCase())}</text>`;if(prefs.sub)body+=`<text x="${W/2}" y="${H*.68}" text-anchor="middle" fill="${prefs.accent}" font-family="monospace" font-size="${H*.1}">${safe(prefs.sub.toUpperCase())}</text>`;}
   const bg=prefs.transparent?'':`<rect width="100%" height="100%" fill="${prefs.bg}"/>`;dl(new Blob([`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}">${bg}${body}</svg>`],{type:'image/svg+xml'}),`${baseName()}.svg`);}
 function exportSpec(){dl(new Blob([JSON.stringify({version:2,...prefs},null,2)],{type:'application/json'}),`${baseName()}-brand-spec.json`);}
 return <ToolShell title="LOGO MAKER 2.0" onExit={onExit} actions={<><button className="wbtn ghost" onClick={exportSpec}>SPEC JSON</button><button className="wbtn ghost" onClick={()=>void exportSvg()}>SVG</button><button className="wbtn" onClick={exportPng}>PNG</button></>}><div className="toolRow" data-testid="logo-maker-2-root"><div className="toolCol" style={{minWidth:300}}><label className="toolField">WORDMARK<input aria-label="Logo wordmark" value={prefs.word} onChange={e=>setPrefs(p=>({...p,word:e.target.value}))}/></label><label className="toolField">TAGLINE<input aria-label="Logo tagline" value={prefs.sub} onChange={e=>setPrefs(p=>({...p,sub:e.target.value}))}/></label>
 <div className="toolField"><label>ICON</label><div style={{display:'grid',gridTemplateColumns:'repeat(5,1fr)',gap:6}}>{choices.map(n=>{const C=ICONS[n];return <button aria-label={`Icon ${n}`} key={n} className={`chip small ${prefs.icon===n?'on':''}`} onClick={()=>setPrefs(p=>({...p,icon:n}))}><C size={16}/></button>;})}</div></div>
 <div className="toolField"><label>LAYOUT</label><div className="toolRow" style={{flexWrap:'wrap'}}>{([['iconLeft','ICON + WORD'],['iconTop','STACKED'],['iconOnly','ICON ONLY'],['wordOnly','WORD ONLY']] as [Layout,string][]).map(([v,l])=><button key={v} className={`chip small ${prefs.layout===v?'on':''}`} onClick={()=>setPrefs(p=>({...p,layout:v}))}>{l}</button>)}</div></div>
 <div className="toolField"><label>BADGE</label><div className="toolRow">{(['none','circle','roundedSquare','square'] as Shape[]).map(v=><button key={v} className={`chip small ${prefs.shape===v?'on':''}`} onClick={()=>setPrefs(p=>({...p,shape:v}))}>{v.toUpperCase()}</button>)}</div></div>
 <div className="toolRow"><label className="toolHint">TEXT <input aria-label="Logo text color" type="color" value={prefs.fg} onChange={e=>setPrefs(p=>({...p,fg:e.target.value}))}/></label><label className="toolHint">ACCENT <input aria-label="Logo accent color" type="color" value={prefs.accent} onChange={e=>setPrefs(p=>({...p,accent:e.target.value}))}/></label><label className="toolHint">BG <input aria-label="Logo background color" type="color" value={prefs.bg} disabled={prefs.transparent} onChange={e=>setPrefs(p=>({...p,bg:e.target.value}))}/></label></div>
 <label className="toolHint"><input aria-label="Transparent background" type="checkbox" checked={prefs.transparent} onChange={e=>setPrefs(p=>({...p,transparent:e.target.checked}))}/> TRANSPARENT BACKGROUND</label><div className="toolRow"><button className={`chip ${prefs.ratio==='wide'?'on':''}`} onClick={()=>setPrefs(p=>({...p,ratio:'wide'}))}>WIDE</button><button className={`chip ${prefs.ratio==='square'?'on':''}`} onClick={()=>setPrefs(p=>({...p,ratio:'square'}))}>SQUARE</button><label className="toolHint">SIZE <select aria-label="Logo size" value={prefs.size} onChange={e=>setPrefs(p=>({...p,size:Number(e.target.value)}))}><option value="480">480</option><option value="720">720</option><option value="1024">1024</option><option value="2048">2048</option></select></label></div></div>
 <div className="toolCol"><div className="toolCanvasWrap" style={{background:prefs.transparent?'repeating-conic-gradient(#222 0 25%,#111 0 50%) 50%/20px 20px':'transparent'}}><canvas ref={canvasRef} style={{maxWidth:'100%',height:'auto'}}/></div>{busy&&<div className="toolHint">Rendering…</div>}</div></div></ToolShell>;
}