import { useCallback, useEffect, useRef, useState, type PointerEvent } from 'react';
import ToolShell from './ToolShell';

type Tool='paint'|'eraser'|'fill'|'picker';
interface PixelDoc{version:2;gridSize:number;grid:(string|null)[];palette:string[];}
const DEFAULT_SIZE=24,DEFAULT_CELL=16;const SIZES=[16,24,32,48];const KEY='xfactor-studio-pixelart2-',LEGACY='xos-studio-pixelart-';
const BASE=['#000000','#1d2b53','#7e2553','#008751','#ab5236','#5f574f','#c2c3c7','#fff1e8','#ff004d','#29adff'];
const blank=(n:number)=>new Array<string|null>(n*n).fill(null);
function load(boardId:string):PixelDoc{try{const raw=localStorage.getItem(KEY+boardId);if(raw){const d=JSON.parse(raw);if(d.version===2&&Array.isArray(d.grid))return{version:2,gridSize:d.gridSize||DEFAULT_SIZE,grid:d.grid,palette:Array.isArray(d.palette)?d.palette:BASE};}const old=localStorage.getItem(LEGACY+boardId);if(old){const d=JSON.parse(old);if(Array.isArray(d.grid)&&d.gridSize)return{version:2,gridSize:d.gridSize,grid:d.grid,palette:BASE};}}catch{}return{version:2,gridSize:DEFAULT_SIZE,grid:blank(DEFAULT_SIZE),palette:BASE};}
function dl(blob:Blob,name:string){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),2500);}
export default function PixelArt({boardId,onExit}:{boardId:string;onExit:()=>void}){
 const [doc,setDoc]=useState<PixelDoc>(()=>load(boardId));const [cellPx,setCellPx]=useState(DEFAULT_CELL);const [tool,setTool]=useState<Tool>('paint');const [color,setColor]=useState(doc.palette[0]||'#000000');const [mirrorX,setMirrorX]=useState(false);const [mirrorY,setMirrorY]=useState(false);const [exportScale,setExportScale]=useState(16);const [history,setHistory]=useState<PixelDoc[]>([]);const [future,setFuture]=useState<PixelDoc[]>([]);const canvasRef=useRef<HTMLCanvasElement>(null);const drawing=useRef(false);const strokeStarted=useRef(false);const {gridSize,grid}=doc;
 useEffect(()=>{const t=setTimeout(()=>{try{localStorage.setItem(KEY+boardId,JSON.stringify(doc));}catch{}},250);return()=>clearTimeout(t);},[doc,boardId]);
 useEffect(()=>{const c=canvasRef.current;if(!c)return;c.width=gridSize*cellPx;c.height=gridSize*cellPx;const ctx=c.getContext('2d');if(!ctx)return;ctx.imageSmoothingEnabled=false;ctx.clearRect(0,0,c.width,c.height);for(let y=0;y<gridSize;y++)for(let x=0;x<gridSize;x++){const v=grid[y*gridSize+x];if(v){ctx.fillStyle=v;ctx.fillRect(x*cellPx,y*cellPx,cellPx,cellPx);}}ctx.strokeStyle='rgba(255,255,255,.08)';for(let i=0;i<=gridSize;i++){const p=i*cellPx+.5;ctx.beginPath();ctx.moveTo(p,0);ctx.lineTo(p,c.height);ctx.stroke();ctx.beginPath();ctx.moveTo(0,p);ctx.lineTo(c.width,p);ctx.stroke();}},[grid,gridSize,cellPx]);
 const commit=useCallback((fn:(d:PixelDoc)=>PixelDoc)=>setDoc(d=>{setHistory(h=>[...h.slice(-39),d]);setFuture([]);return fn(d);}),[]);
 function undo(){setHistory(h=>{if(!h.length)return h;const prev=h[h.length-1];setFuture(f=>[doc,...f]);setDoc(prev);return h.slice(0,-1);});}function redo(){setFuture(f=>{if(!f.length)return f;const next=f[0];setHistory(h=>[...h,doc]);setDoc(next);return f.slice(1);});}
 function indexFrom(clientX:number,clientY:number){const c=canvasRef.current;if(!c)return null;const r=c.getBoundingClientRect();const x=Math.floor((clientX-r.left)*c.width/r.width/cellPx),y=Math.floor((clientY-r.top)*c.height/r.height/cellPx);return x>=0&&y>=0&&x<gridSize&&y<gridSize?{x,y,idx:y*gridSize+x}:null;}
 function points(x:number,y:number){const out=[[x,y]];if(mirrorX)out.push([gridSize-1-x,y]);if(mirrorY)out.push([x,gridSize-1-y]);if(mirrorX&&mirrorY)out.push([gridSize-1-x,gridSize-1-y]);return out;}
 function drawAt(clientX:number,clientY:number){const p=indexFrom(clientX,clientY);if(!p)return;if(tool==='picker'){const v=doc.grid[p.idx];if(v){setColor(v);setTool('paint');}return;}if(tool==='fill'){const target=doc.grid[p.idx],value=color;if(target===value)return;commit(d=>{const next=[...d.grid],q=[p.idx],seen=new Set<number>();while(q.length){const i=q.pop()!;if(seen.has(i)||next[i]!==target)continue;seen.add(i);next[i]=value;const x=i%d.gridSize,y=(i/d.gridSize)|0;if(x>0)q.push(i-1);if(x<d.gridSize-1)q.push(i+1);if(y>0)q.push(i-d.gridSize);if(y<d.gridSize-1)q.push(i+d.gridSize);}return{...d,grid:next};});setTool('paint');return;}const value=tool==='eraser'?null:color;setDoc(d=>{const next=[...d.grid];for(const [x,y] of points(p.x,p.y))next[y*d.gridSize+x]=value;return{...d,grid:next};});}
 function pointerDown(e:PointerEvent<HTMLCanvasElement>){drawing.current=true;strokeStarted.current=true;setHistory(h=>[...h.slice(-39),doc]);setFuture([]);e.currentTarget.setPointerCapture(e.pointerId);drawAt(e.clientX,e.clientY);if(tool==='fill'||tool==='picker')drawing.current=false;}function pointerMove(e:PointerEvent<HTMLCanvasElement>){if(drawing.current)drawAt(e.clientX,e.clientY);}function pointerUp(e:PointerEvent<HTMLCanvasElement>){drawing.current=false;strokeStarted.current=false;if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);}
 function transform(kind:'flipH'|'flipV'|'rotR'){commit(d=>{const n=d.gridSize,next=blank(n);for(let y=0;y<n;y++)for(let x=0;x<n;x++){const v=d.grid[y*n+x];let nx=x,ny=y;if(kind==='flipH')nx=n-1-x;if(kind==='flipV')ny=n-1-y;if(kind==='rotR'){nx=n-1-y;ny=x;}next[ny*n+nx]=v;}return{...d,grid:next};});}
 function changeSize(n:number){if(n===gridSize)return;if(grid.some(Boolean)&&!window.confirm('Changing grid size will clear the current canvas. Continue?'))return;commit(d=>({...d,gridSize:n,grid:blank(n)}));}
 function clear(){if(!grid.some(Boolean)||!window.confirm('Clear the entire canvas?'))return;commit(d=>({...d,grid:blank(d.gridSize)}));}
 function exportPng(){const n=gridSize*exportScale,c=document.createElement('canvas');c.width=n;c.height=n;const ctx=c.getContext('2d');if(!ctx)return;ctx.imageSmoothingEnabled=false;for(let y=0;y<gridSize;y++)for(let x=0;x<gridSize;x++){const v=grid[y*gridSize+x];if(v){ctx.fillStyle=v;ctx.fillRect(x*exportScale,y*exportScale,exportScale,exportScale);}}c.toBlob(b=>b&&dl(b,`pixelart-${gridSize}x${gridSize}.png`),'image/png');}
 function exportJson(){dl(new Blob([JSON.stringify(doc,null,2)],{type:'application/json'}),'pixelart.json');}function importJson(file:File){file.text().then(text=>{try{const d=JSON.parse(text);if(d.version!==2||!Number.isInteger(d.gridSize)||!Array.isArray(d.grid)||d.grid.length!==d.gridSize*d.gridSize)throw new Error();commit(()=>({...d,palette:Array.isArray(d.palette)?d.palette:BASE}));}catch{window.alert('Invalid Pixel Art JSON');}});}
 function addPalette(hex:string){setColor(hex);setTool('paint');if(!doc.palette.includes(hex))setDoc(d=>({...d,palette:[...d.palette,hex].slice(-20)}));}
 return <ToolShell title="PIXEL ART 2.0" onExit={onExit} actions={<><button className="wbtn ghost" onClick={undo} disabled={!history.length}>UNDO</button><button className="wbtn ghost" onClick={redo} disabled={!future.length}>REDO</button><button className="wbtn ghost" onClick={clear}>CLEAR</button><button className="wbtn" onClick={exportPng}>EXPORT PNG</button></>}><div className="toolCol" data-testid="pixel-art-2-root"><div className="toolRow" style={{flexWrap:'wrap'}}>{(['paint','eraser','fill','picker'] as Tool[]).map(t=><button key={t} className={`chip ${tool===t?'on':''}`} onClick={()=>setTool(t)}>{t.toUpperCase()}</button>)}<label className="toolHint"><input aria-label="Mirror horizontal" type="checkbox" checked={mirrorX} onChange={e=>setMirrorX(e.target.checked)}/> MIRROR X</label><label className="toolHint"><input aria-label="Mirror vertical" type="checkbox" checked={mirrorY} onChange={e=>setMirrorY(e.target.checked)}/> MIRROR Y</label></div>
 <div className="toolRow" style={{flexWrap:'wrap'}}><span className="rsub">GRID</span>{SIZES.map(n=><button key={n} className={`chip ${gridSize===n?'on':''}`} onClick={()=>changeSize(n)}>{n}</button>)}<label className="toolHint">ZOOM {cellPx}<input aria-label="Pixel zoom" type="range" min="4" max="28" value={cellPx} onChange={e=>setCellPx(Number(e.target.value))}/></label></div>
 <div className="toolSwatchGrid">{doc.palette.map(h=><button aria-label={`Color ${h}`} key={h} className={`toolSwatch ${color===h&&tool==='paint'?'on':''}`} onClick={()=>{setColor(h);setTool('paint')}}><span className="sw" style={{display:'block',background:h}}/></button>)}<label className="toolSwatch" title="Custom color"><input aria-label="Custom pixel color" type="color" value={color} onChange={e=>addPalette(e.target.value)} style={{width:'100%',height:'100%',border:0,padding:0}}/></label></div>
 <div className="toolRow"><button className="toolBtn" onClick={()=>transform('flipH')}>Flip H</button><button className="toolBtn" onClick={()=>transform('flipV')}>Flip V</button><button className="toolBtn" onClick={()=>transform('rotR')}>Rotate 90°</button><label className="toolHint">EXPORT SCALE <select aria-label="Pixel export scale" value={exportScale} onChange={e=>setExportScale(Number(e.target.value))}><option value="4">4×</option><option value="8">8×</option><option value="16">16×</option><option value="32">32×</option></select></label><button className="toolBtn" onClick={exportJson}>JSON</button><label className="toolBtn">IMPORT JSON<input aria-label="Pixel art JSON" type="file" accept="application/json" hidden onChange={e=>e.target.files?.[0]&&importJson(e.target.files[0])}/></label></div>
 <div className="toolCanvasWrap"><canvas ref={canvasRef} onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={pointerUp} style={{cursor:tool==='picker'?'copy':tool==='eraser'?'cell':'crosshair',touchAction:'none',imageRendering:'pixelated'}}/></div><div className="toolHint">{gridSize}×{gridSize} · paint, fill, sample, mirror, transform, and export. Saved automatically for this board.</div></div></ToolShell>;
}