import { useEffect, useRef, useState } from 'react';
import ToolShell from './ToolShell';

type Format='png'|'jpeg'|'webp';
interface Selection{x0:number;y0:number;x1:number;y1:number;}
interface Settings{brightness:number;contrast:number;saturation:number;format:Format;quality:number;lockAspect:boolean;}
const KEY='xfactor-studio-photoedit2-';const LEGACY='xos-studio-photoedit-';
const defaults:Settings={brightness:0,contrast:0,saturation:0,format:'png',quality:90,lockAspect:true};
function load(boardId:string):Settings{try{const raw=localStorage.getItem(`${KEY}${boardId}`);if(raw)return{...defaults,...JSON.parse(raw)};const old=localStorage.getItem(`${LEGACY}${boardId}`);if(old)return{...defaults,...JSON.parse(old)};}catch{}return defaults;}
function download(blob:Blob,name:string){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),3000);}

export default function QuickPhotoEditor({boardId,onExit}:{boardId:string;onExit:()=>void}){
 const canvasRef=useRef<HTMLCanvasElement>(null);const originalRef=useRef<string>('');const dragging=useRef(false);const [settings,setSettings]=useState<Settings>(()=>load(boardId));const [hasImage,setHasImage]=useState(false);const [selection,setSelection]=useState<Selection|null>(null);const [status,setStatus]=useState('AWAITING IMAGE UPLOAD');const [history,setHistory]=useState<string[]>([]);const [future,setFuture]=useState<string[]>([]);const [resizeW,setResizeW]=useState(0);const [resizeH,setResizeH]=useState(0);
 useEffect(()=>{try{localStorage.setItem(`${KEY}${boardId}`,JSON.stringify(settings));}catch{}},[boardId,settings]);
 const canvas=()=>canvasRef.current;const snap=()=>canvas()?.toDataURL('image/png')||'';
 function checkpoint(){const s=snap();if(s)setHistory(h=>[...h.slice(-14),s]);setFuture([]);}
 function restore(data:string){const c=canvas();if(!c||!data)return;const img=new Image();img.onload=()=>{c.width=img.width;c.height=img.height;c.getContext('2d')?.drawImage(img,0,0);setResizeW(c.width);setResizeH(c.height);setSelection(null);};img.src=data;}
 function undo(){if(!history.length)return;const current=snap(),prev=history[history.length-1];setHistory(h=>h.slice(0,-1));if(current)setFuture(f=>[current,...f].slice(0,15));restore(prev);setStatus('UNDO');}
 function redo(){if(!future.length)return;const current=snap(),next=future[0];if(current)setHistory(h=>[...h.slice(-14),current]);setFuture(f=>f.slice(1));restore(next);setStatus('REDO');}
 function upload(file:File){const u=URL.createObjectURL(file),img=new Image();img.onload=()=>{const c=canvas();if(!c)return;c.width=img.naturalWidth;c.height=img.naturalHeight;c.getContext('2d')?.drawImage(img,0,0);originalRef.current=c.toDataURL('image/png');setResizeW(c.width);setResizeH(c.height);setHasImage(true);setHistory([]);setFuture([]);setSelection(null);setStatus(`${img.naturalWidth}×${img.naturalHeight} IMAGE LOADED`);URL.revokeObjectURL(u);};img.onerror=()=>{URL.revokeObjectURL(u);setStatus('COULD NOT LOAD IMAGE');};img.src=u;}
 function rotate(){const c=canvas();if(!c)return;checkpoint();const temp=document.createElement('canvas');temp.width=c.height;temp.height=c.width;const x=temp.getContext('2d');if(!x)return;x.translate(temp.width,0);x.rotate(Math.PI/2);x.drawImage(c,0,0);c.width=temp.width;c.height=temp.height;c.getContext('2d')?.drawImage(temp,0,0);setResizeW(c.width);setResizeH(c.height);setSelection(null);setStatus('ROTATED 90°');}
 function flip(horizontal:boolean){const c=canvas();if(!c)return;checkpoint();const temp=document.createElement('canvas');temp.width=c.width;temp.height=c.height;const x=temp.getContext('2d');if(!x)return;x.save();if(horizontal){x.scale(-1,1);x.drawImage(c,-c.width,0);}else{x.scale(1,-1);x.drawImage(c,0,-c.height);}x.restore();c.getContext('2d')?.clearRect(0,0,c.width,c.height);c.getContext('2d')?.drawImage(temp,0,0);setStatus(horizontal?'FLIPPED HORIZONTAL':'FLIPPED VERTICAL');}
 function point(e:React.PointerEvent<HTMLCanvasElement>){const c=canvas(),r=c?.getBoundingClientRect();if(!c||!r)return{x:0,y:0};return{x:Math.max(0,Math.min(c.width,(e.clientX-r.left)*c.width/r.width)),y:Math.max(0,Math.min(c.height,(e.clientY-r.top)*c.height/r.height))};}
 function crop(){const c=canvas();if(!c||!selection)return;const sx=Math.round(Math.min(selection.x0,selection.x1)),sy=Math.round(Math.min(selection.y0,selection.y1)),w=Math.round(Math.abs(selection.x1-selection.x0)),h=Math.round(Math.abs(selection.y1-selection.y0));if(w<2||h<2){setStatus('SELECTION TOO SMALL');return;}checkpoint();const t=document.createElement('canvas');t.width=w;t.height=h;t.getContext('2d')?.drawImage(c,sx,sy,w,h,0,0,w,h);c.width=w;c.height=h;c.getContext('2d')?.drawImage(t,0,0);setResizeW(w);setResizeH(h);setSelection(null);setStatus('CROP APPLIED');}
 function adjust(){const c=canvas(),ctx=c?.getContext('2d');if(!c||!ctx)return;checkpoint();const im=ctx.getImageData(0,0,c.width,c.height),d=im.data,contrast=Math.max(-254,Math.min(254,settings.contrast)),factor=(259*(contrast+255))/(255*(259-contrast)),sat=1+settings.saturation/100;for(let i=0;i<d.length;i+=4){let r=factor*(d[i]+settings.brightness-128)+128,g=factor*(d[i+1]+settings.brightness-128)+128,b=factor*(d[i+2]+settings.brightness-128)+128;const gray=.299*r+.587*g+.114*b;r=gray+(r-gray)*sat;g=gray+(g-gray)*sat;b=gray+(b-gray)*sat;d[i]=Math.max(0,Math.min(255,r));d[i+1]=Math.max(0,Math.min(255,g));d[i+2]=Math.max(0,Math.min(255,b));}ctx.putImageData(im,0,0);setStatus('ADJUSTMENTS APPLIED');}
 function resize(){const c=canvas();if(!c||resizeW<1||resizeH<1)return;if(resizeW===c.width&&resizeH===c.height)return;checkpoint();const t=document.createElement('canvas');t.width=resizeW;t.height=resizeH;const x=t.getContext('2d');if(!x)return;x.imageSmoothingEnabled=true;x.imageSmoothingQuality='high';x.drawImage(c,0,0,resizeW,resizeH);c.width=resizeW;c.height=resizeH;c.getContext('2d')?.drawImage(t,0,0);setSelection(null);setStatus(`RESIZED TO ${resizeW}×${resizeH}`);}
 function changeDim(kind:'w'|'h',n:number){const c=canvas();if(!c)return;if(kind==='w'){setResizeW(n);if(settings.lockAspect&&n>0)setResizeH(Math.max(1,Math.round(n*c.height/c.width)));}else{setResizeH(n);if(settings.lockAspect&&n>0)setResizeW(Math.max(1,Math.round(n*c.width/c.height)));}}
 function reset(){if(!originalRef.current)return;checkpoint();restore(originalRef.current);setStatus('RESET TO ORIGINAL');}
 function exportImage(){const c=canvas();if(!c)return;const mime=settings.format==='png'?'image/png':settings.format==='jpeg'?'image/jpeg':'image/webp';c.toBlob(b=>{if(!b)return;const ext=settings.format==='jpeg'?'jpg':settings.format;download(b,`edited.${ext}`);setStatus(`EXPORTED ${settings.format.toUpperCase()} · ${Math.round(b.size/1024)} KB`);},mime,settings.format==='png'?undefined:settings.quality/100);}
 let overlay:React.CSSProperties|undefined;if(selection&&canvas()){const c=canvas()!,r=c.getBoundingClientRect(),sx=r.width/c.width,sy=r.height/c.height;overlay={position:'absolute',left:Math.min(selection.x0,selection.x1)*sx,top:Math.min(selection.y0,selection.y1)*sy,width:Math.abs(selection.x1-selection.x0)*sx,height:Math.abs(selection.y1-selection.y0)*sy,background:'rgba(0,245,255,.14)',border:'1px dashed var(--cyan)',pointerEvents:'none'};}
 return <ToolShell title="QUICK PHOTO EDITOR 2.0" onExit={onExit}><div className="toolCol" data-testid="quick-photo-2-root"><div className="toolRow"><label className="toolDrop"><input aria-label="Photo file" type="file" accept="image/*" hidden onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/>UPLOAD PHOTO</label><button className="toolBtn" disabled={!history.length} onClick={undo}>Undo</button><button className="toolBtn" disabled={!future.length} onClick={redo}>Redo</button><button className="toolBtn" disabled={!hasImage} onClick={reset}>Reset</button></div>
 <div className="toolCanvasWrap" style={{position:'relative',maxWidth:720}}><canvas ref={canvasRef} style={{maxWidth:680,width:'100%',height:'auto',touchAction:'none'}} onPointerDown={e=>{if(!hasImage)return;const p=point(e);dragging.current=true;setSelection({x0:p.x,y0:p.y,x1:p.x,y1:p.y});e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(!dragging.current)return;const p=point(e);setSelection(s=>s?{...s,x1:p.x,y1:p.y}:s);}} onPointerUp={()=>dragging.current=false}/>{overlay&&<div style={overlay}/>}</div><div className="toolHint">{status}</div>
 <div className="rsub">TRANSFORM</div><div className="toolRow"><button className="wbtn" disabled={!hasImage} onClick={rotate}>ROTATE 90°</button><button className="wbtn" disabled={!hasImage} onClick={()=>flip(true)}>FLIP H</button><button className="wbtn" disabled={!hasImage} onClick={()=>flip(false)}>FLIP V</button><button className="wbtn" disabled={!selection} onClick={crop}>CROP SELECTION</button><button className="wbtn ghost" disabled={!selection} onClick={()=>setSelection(null)}>CLEAR CROP</button></div>
 <div className="rsub">RESIZE</div><div className="toolRow"><label className="toolHint">W <input aria-label="Resize width" type="number" min="1" value={resizeW||''} onChange={e=>changeDim('w',Number(e.target.value))} style={{width:88}}/></label><label className="toolHint">H <input aria-label="Resize height" type="number" min="1" value={resizeH||''} onChange={e=>changeDim('h',Number(e.target.value))} style={{width:88}}/></label><label className="toolHint"><input type="checkbox" checked={settings.lockAspect} onChange={e=>setSettings(s=>({...s,lockAspect:e.target.checked}))}/> LOCK ASPECT</label><button className="wbtn" disabled={!hasImage} onClick={resize}>APPLY RESIZE</button></div>
 <div className="rsub">ADJUST</div>{([['brightness',-100,100],['contrast',-100,100],['saturation',-100,100]] as const).map(([k,min,max])=><div className="toolField" key={k}><label>{k.toUpperCase()} ({settings[k]})</label><input aria-label={k} type="range" min={min} max={max} value={settings[k]} onChange={e=>setSettings(s=>({...s,[k]:Number(e.target.value)}))}/></div>)}<button className="wbtn" disabled={!hasImage} onClick={adjust}>APPLY ADJUSTMENTS</button>
 <div className="rsub">EXPORT</div><div className="toolRow">{(['png','jpeg','webp'] as const).map(f=><button key={f} className={`chip ${settings.format===f?'on':''}`} onClick={()=>setSettings(s=>({...s,format:f}))}>{f.toUpperCase()}</button>)}{settings.format!=='png'&&<label className="toolHint">QUALITY {settings.quality}<input aria-label="Export quality" type="range" min="1" max="100" value={settings.quality} onChange={e=>setSettings(s=>({...s,quality:Number(e.target.value)}))}/></label>}<button className="wbtn" disabled={!hasImage} onClick={exportImage}>EXPORT</button></div>
 </div></ToolShell>;
}