use reqwest::{Client, Method, StatusCode, Url};
use serde_json::{json, Value};
use std::{env, fs, path::PathBuf, process::Command, time::{Duration, SystemTime, UNIX_EPOCH}};
const ADAPTER_VERSION:&str="1.0.0";const PRODUCT_ID:&str="planetx.xfactor-os";const MAX_PAYLOAD_BYTES:usize=2*1024*1024;
fn hub_home()->Result<PathBuf,String>{let user=env::var_os("USERPROFILE").or_else(||env::var_os("HOME")).ok_or_else(||"No user home directory is available.".to_string())?;Ok(PathBuf::from(user).join("Documents").join("fabriX"))}
fn port_path()->Result<PathBuf,String>{Ok(hub_home()?.join("Registry").join("hub-port.txt"))}fn token_path()->Result<PathBuf,String>{Ok(hub_home()?.join("Registry").join("local-api-token.txt"))}
fn read_port()->Result<u16,String>{let raw=fs::read_to_string(port_path()?).map_err(|_|"fabriX Hub port file was not found.".to_string())?;let port=raw.trim().parse::<u16>().map_err(|_|"fabriX Hub published an invalid loopback port.".to_string())?;if port==0{return Err("fabriX Hub published an invalid loopback port.".to_string())}Ok(port)}
fn hub_url(path:&str)->Result<Url,String>{let port=read_port()?;let mut url=Url::parse(&format!("http://127.0.0.1:{port}/")).map_err(|e|e.to_string())?;url.set_path(path.trim_start_matches('/'));Ok(url)}
fn client()->Result<Client,String>{Client::builder().timeout(Duration::from_secs(4)).redirect(reqwest::redirect::Policy::none()).build().map_err(|e|format!("Could not create fabriX loopback client: {e}"))}
fn read_token()->Option<String>{fs::read_to_string(token_path().ok()?).ok().map(|v|v.trim().to_string()).filter(|v|!v.is_empty())}
fn valid_product_id(v:&str)->bool{!v.is_empty()&&v.len()<=128&&v.chars().all(|c|c.is_ascii_alphanumeric()||matches!(c,'.'|'-'|'_'))}
fn safe_id(v:&str)->String{let filtered=v.chars().filter(|c|c.is_ascii_alphanumeric()||matches!(c,'.'|'-'|'_')).take(80).collect::<String>();let mut out=filtered.trim_start_matches('.').to_string();if out.is_empty(){out.push_str("xfactor")}out}
fn payload_size(payload:&Value)->Result<Vec<u8>,String>{let bytes=serde_json::to_vec_pretty(payload).map_err(|e|format!("Invalid fabriX payload: {e}"))?;if bytes.len()>MAX_PAYLOAD_BYTES{return Err("fabriX payload exceeds the 2 MiB local handoff limit.".to_string())}Ok(bytes)}
fn write_inbox(kind:&str,payload:&Value)->Result<Value,String>{let home=hub_home()?;let dir=match kind{"project"=>home.join("Projects").join("Inbox"),"artifact"=>home.join("Artifacts").join("Inbox"),_=>return Err("Unsupported fabriX inbox kind.".to_string())};fs::create_dir_all(&dir).map_err(|e|format!("Could not create fabriX inbox: {e}"))?;let id=payload.get(if kind=="project"{"project_id"}else{"artifact_id"}).and_then(Value::as_str).unwrap_or(PRODUCT_ID);let stamp=SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default().as_millis();let path=dir.join(format!("{}-{stamp}.json",safe_id(id)));fs::write(&path,payload_size(payload)?).map_err(|e|format!("Could not stage fabriX handoff: {e}"))?;Ok(json!({"ok":true,"mode":"file-drop","path":path.to_string_lossy(),"message":"Staged in the canonical fabriX Home for Hub pickup."}))}
async fn post_json(path:&str,payload:&Value)->Result<Option<Value>,String>{let mut request=client()?.request(Method::POST,hub_url(path)?).json(payload);if let Some(token)=read_token(){request=request.bearer_auth(token)}let response=match request.send().await{Ok(v)=>v,Err(_)=>return Ok(None)};if matches!(response.status(),StatusCode::NOT_FOUND|StatusCode::METHOD_NOT_ALLOWED){return Ok(None)}let status=response.status();let body=response.json::<Value>().await.unwrap_or_else(|_|json!({"ok":status.is_success()}));if !status.is_success(){return Err(format!("fabriX Hub rejected the handoff ({status}): {}",body.get("error").and_then(Value::as_str).unwrap_or("unknown error")))}Ok(Some(json!({"ok":true,"mode":"rpc","status":status.as_u16(),"message":"Published through the fabriX loopback adapter.","response":body})))}
#[tauri::command]pub fn fabrix_describe()->Result<Value,String>{serde_json::from_str(include_str!("../../fabrix.manifest.json")).map_err(|e|format!("Embedded fabriX manifest is invalid: {e}"))}
#[tauri::command]pub async fn fabrix_health()->Value{let home=match hub_home(){Ok(v)=>v,Err(e)=>return json!({"connected":false,"adapter_version":ADAPTER_VERSION,"transport":"disconnected","authenticated":false,"error":e})};let authenticated=read_token().is_some();let url=match hub_url("/__fabrix/status"){Ok(v)=>v,Err(e)=>return json!({"connected":false,"adapter_version":ADAPTER_VERSION,"transport":"disconnected","authenticated":authenticated,"hub_home":home.to_string_lossy(),"error":e})};let c=match client(){Ok(v)=>v,Err(e)=>return json!({"connected":false,"adapter_version":ADAPTER_VERSION,"transport":"disconnected","authenticated":authenticated,"hub_home":home.to_string_lossy(),"error":e})};match c.get(url).send().await{Ok(response)if response.status().is_success()=>{let status=response.json::<Value>().await.unwrap_or_else(|_|json!({}));json!({"connected":true,"hub_version":status.get("version").and_then(Value::as_str),"adapter_version":ADAPTER_VERSION,"transport":if authenticated{"loopback-authenticated"}else{"loopback-rc3"},"authenticated":authenticated,"hub_home":home.to_string_lossy()})},Ok(response)=>json!({"connected":false,"adapter_version":ADAPTER_VERSION,"transport":"disconnected","authenticated":authenticated,"hub_home":home.to_string_lossy(),"error":format!("fabriX Hub returned {}",response.status())}),Err(e)=>json!({"connected":false,"adapter_version":ADAPTER_VERSION,"transport":"disconnected","authenticated":authenticated,"hub_home":home.to_string_lossy(),"error":format!("fabriX Hub is not reachable: {e}")})}}
#[tauri::command]pub async fn fabrix_products()->Value{let url=match hub_url("/__fabrix/products"){Ok(v)=>v,Err(e)=>return json!({"connected":false,"products":[],"error":e})};match client(){Ok(c)=>match c.get(url).send().await{Ok(response)if response.status().is_success()=>{let products=response.json::<Value>().await.unwrap_or_else(|_|json!([]));json!({"connected":true,"products":products})},Ok(response)=>json!({"connected":false,"products":[],"error":format!("fabriX Hub returned {}",response.status())}),Err(e)=>json!({"connected":false,"products":[],"error":format!("fabriX Hub is not reachable: {e}")})},Err(e)=>json!({"connected":false,"products":[],"error":e})}}
#[tauri::command]pub async fn fabrix_open_product(product_id:String)->Result<Value,String>{if !valid_product_id(&product_id){return Err("Invalid fabriX product id.".to_string())}let mut url=hub_url("/__fabrix/open")?;url.query_pairs_mut().append_pair("id",&product_id);let response=client()?.post(url).send().await.map_err(|e|format!("Could not reach fabriX Hub: {e}"))?;let status=response.status();let body=response.json::<Value>().await.unwrap_or_else(|_|json!({}));if !status.is_success(){return Err(format!("fabriX Hub could not open product ({status}): {}",body.get("error").and_then(Value::as_str).unwrap_or("unknown error")))}Ok(body)}
#[tauri::command]pub fn fabrix_launch_hub(uri:String)->Result<Value,String>{let lower=uri.to_ascii_lowercase();if uri.len()>2048||!lower.starts_with("fabrix://"){return Err("Only bounded fabrix:// Hub links are accepted.".to_string())}#[cfg(target_os="windows")]{Command::new("explorer.exe").arg(&uri).spawn().map_err(|e|format!("Could not launch fabriX Hub: {e}"))?;Ok(json!({"ok":true,"uri":uri}))}#[cfg(not(target_os="windows"))]{{let _=uri;Err("fabriX Hub launch is currently supported by the Windows desktop build.".to_string())}}}
#[tauri::command]pub async fn fabrix_publish_project(payload:Value)->Result<Value,String>{payload_size(&payload)?;if let Some(result)=post_json("/__fabrix/projects",&payload).await?{return Ok(result)}write_inbox("project",&payload)}
#[tauri::command]pub async fn fabrix_publish_artifact(payload:Value)->Result<Value,String>{payload_size(&payload)?;if let Some(result)=post_json("/__fabrix/artifacts",&payload).await?{return Ok(result)}write_inbox("artifact",&payload)}
#[tauri::command]pub fn fabrix_entitlement_status()->Value{json!({"product_id":PRODUCT_ID,"authority":"xfactor-os","status":"delegated","registration_grants_entitlement":false,"message":"fabriX discovery, registration and installation never manufacture an xFactor.OS software entitlement."})}
#[tauri::command]pub fn fabrix_pending_context()->Option<Value>{let args=env::args().collect::<Vec<_>>();for(index,arg)in args.iter().enumerate(){if arg=="--fabrix-context"{if let Some(next)=args.get(index+1){if next.len()<=16_384{return serde_json::from_str::<Value>(next).ok().or_else(||Some(json!({"raw":next})))}}}if arg.to_ascii_lowercase().starts_with("fabrix://")&&arg.len()<=2048{return Some(json!({"uri":arg}))}}None}
#[cfg(test)]mod tests{use super::*;#[test]fn product_ids_are_bounded(){assert!(valid_product_id("xupply.project-control-plane"));assert!(!valid_product_id("../bad"));assert!(!valid_product_id(""));}#[test]fn inbox_names_never_preserve_paths(){assert_eq!(safe_id("../../monster x"),"monsterx");}}
